"""This makes the name column unique and adds two new columns.

These columns are the filename columns (where the emote is in the filesystem)
and the verified column that will have future use when we have an approval
queue.

Revision ID: 02b220253f88
Revises: d2ba841a262f
Create Date: 2016-08-21 21:47:26.520022

"""

# revision identifiers, used by Alembic.
revision = '02b220253f88'
down_revision = 'd2ba841a262f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emote', sa.Column('filename', sa.String(length=32), nullable=True))
    op.add_column('emote', sa.Column('verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_emote_verified'), 'emote', ['verified'], unique=False)
    op.drop_index('ix_emote_name', table_name='emote')
    op.create_index(op.f('ix_emote_name'), 'emote', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emote_name'), table_name='emote')
    op.create_index('ix_emote_name', 'emote', ['name'], unique=False)
    op.drop_index(op.f('ix_emote_verified'), table_name='emote')
    op.drop_column('emote', 'verified')
    op.drop_column('emote', 'filename')
    ### end Alembic commands ###
