"""Initial migration.

Revision ID: d2ba841a262f
Revises: None
Create Date: 2016-08-21 20:26:31.773575

"""

# revision identifiers, used by Alembic.
revision = 'd2ba841a262f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emote_name'), 'emote', ['name'], unique=False)
    op.create_index(op.f('ix_emote_owner_id'), 'emote', ['owner_id'], unique=False)
    op.create_index(op.f('ix_emote_shared'), 'emote', ['shared'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emote_shared'), table_name='emote')
    op.drop_index(op.f('ix_emote_owner_id'), table_name='emote')
    op.drop_index(op.f('ix_emote_name'), table_name='emote')
    op.drop_table('emote')
    ### end Alembic commands ###
